### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mrkog3** [garrytrinder/msteams-azure-search-openai-demo#13]
Hello, I have everything configured to work locally in the sandbox, but when sending queries sometimes it answers the questions correctly and other times it has the error:

  [onTurnError] unhandled error: Error: Internal Server Error

then in teams it looks like this:
![image](https://github.com/garrytrinder/msteams-azure-search-openai-demo/assets/141848002/ec3e1416-b4f2-4f5a-8e6d-5fb320cf2a30)
but after i haver a response for the same question

I find it strange that sometimes it answers and sometimes it doesn't to the same question, is there a way to fix this? or it will stop happening if I leave it on a server and not local

**Comment by garrytrinder** [comment]
Apologies for the trouble. Let me take a look.

**Comment by garrytrinder** [comment]
@mrkog3 thank you for raising this issue. I've just pushed a fix for this. It was caused by a change made to the API endpoint.

I've also pushed a few updates to resolve some other issues, such as #14 & #15.

If you run into any other issues, please do raise an issue and I will look into them for you.

Thanks again for taking the time to raise the issue and apologies for the inconvenience.
